### ISSUE TITLE
AES

### ISSUE THREAD

**Issue by elliotwutingfeng** [bitanon/cipherlib#1]
Support AES. Possibly the same modes that pointycastle supports?

**Comment by dipu-bd** [comment]
It is under development

**Comment by dipu-bd** [comment]
![image](https://github.com/bitanon/cipherlib/assets/5158124/ec668148-f569-4682-9cc0-5c1be9f2bdc5)

**Comment by dipu-bd** [comment]
TODO:
- [ ] Mode: XTS
- [ ] Mode: GCM
- [ ] MODE: CCM
- [ ] MODE: CMAC
- [ ] Mode: EAX
- [ ] Mode: OCB

**Comment by dipu-bd** [comment]
Mode | Category | Popularity | Primary Usage
-- | -- | -- | --
GCM | Authenticated (AEAD) | 10 / 10 | Modern Web (TLS 1.3), VPNs, Cloud Storage
XTS | Storage Encryption | 9 / 10 | BitLocker, FileVault, SSD Hardware Encryption
CTR | Confidentiality (Stream) | 8 / 10 | High-speed networking, Random-access files
CBC | Confidentiality (Chained) | 6 / 10 | Legacy systems, Older VPN protocols
CCM | Authenticated (AEAD) | 6 / 10 | IoT, Wi-Fi Security (WPA2/WPA3), Bluetooth
GCM-SIV | Misuse-Resistant AEAD | 5 / 10 | Systems prone to "nonce" reuse errors
CFB / OFB | Confidentiality (Stream) | 3 / 10 | Low-latency terminal data, Older protocols
KW / KWP | Key Wrapping | 4 / 10 | Hardware Security Modules (HSM), Key Management
FF1 / FF3 | Format Preserving | 4 / 10 | Database security (Credit cards, SSNs)
ECB | Basic Block | 1 / 10 | DEPRECATED (Only for single-block keys)

**Comment by dipu-bd** [comment]
https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf
